name: Run Every 5 Minutes

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every 5 minutes

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Example Step
        run: echo "This is running every 5 minutes!"
