name: Renode ESP32

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Renode
      run: |
        wget https://github.com/renode/renode/releases/download/v1.12.0/renode-1.12.0.linux-portable.tar.gz
        tar -xzf renode-1.12.0.linux-portable.tar.gz
        
        echo =========================
        ls ./renode_1.12.0_portable
        export PATH=$PATH:$PWD/renode_1.12.0_portable
        # sudo mv renode_1.12.0_portable /opt/renode
        # echo 'export PATH=$PATH:/opt/renode' >> $GITHUB_ENV

        renode_1.12.0_portable/renode --verbose esp32.resc --run-script=script.resc

    - name: Run Renode script
      run: renode --verbose esp32.resc --run-script=script.resc
