name: Sync repo
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: congneb/example_staging
          token: ${{ secrets.CONG_TOKEN }}
          fetch-depth: 0
          
      # - name: Do sync
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"   
        
      #     git remote add public-repo https://github.com/congneb/test_template.git

      #     git commit -m "Auto sync"
      #     git push public-repo master

        # run: |
        #   git config --global user.name "github-actions[bot]"
        #   git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"   
          
        #   git remote add upstream https://github.com/congneb/esp32.git
        #   git fetch origin upstream
        #   # merge current repo in to upstream repo, branch: master
        #   git merge upstream/master
          
        #   # Push to downstream repo congneb/test_template 
        #   git add .
        #   git commit -m "Merge updates from template repository"
          
        #   git push origin master
