name: Sync repo
on:
  workflow_dispatch:
  
  push:
  
jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: congneb/test_template
          token: ${{ secrets.CONG_TOKEN }}
          
      - name: Do sync
        run: |
          git remote add upstream https://github.com/congneb/esp32.git
          git fetch upstream
          git merge upstream/master
          git push origin master
